# Generated by Django 5.1.15 on 2026-03-17 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-date', 'number'], 'verbose_name': 'Договор', 'verbose_name_plural': 'Договоры'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'ordering': ['organization_type', 'full_name'], 'verbose_name': 'Вид работ', 'verbose_name_plural': 'Виды работ'},
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='powerofattorney',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='contract',
            name='organization_type',
            field=models.CharField(choices=[('GC', 'ГК (Группа компаний)'), ('CHOU', 'ЧОУ (Частное образовательное учреждение)')], default='GC', max_length=10, verbose_name='Тип организации'),
        ),
        migrations.AddField(
            model_name='powerofattorney',
            name='organization_type',
            field=models.CharField(choices=[('GC', 'ГК (Группа компаний)'), ('CHOU', 'ЧОУ (Частное образовательное учреждение)')], default='GC', max_length=10, verbose_name='Тип организации'),
        ),
        migrations.AddField(
            model_name='worktype',
            name='organization_type',
            field=models.CharField(choices=[('GC', 'ГК (Группа компаний)'), ('CHOU', 'ЧОУ (Частное образовательное учреждение)')], default='GC', max_length=10, verbose_name='Тип организации'),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('organization_type', 'number', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='powerofattorney',
            unique_together={('organization_type', 'number', 'date')},
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['organization_type'], name='directories_organiz_db1e99_idx'),
        ),
        migrations.AddIndex(
            model_name='powerofattorney',
            index=models.Index(fields=['organization_type'], name='directories_organiz_128dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='worktype',
            index=models.Index(fields=['organization_type'], name='directories_organiz_eab24d_idx'),
        ),
        migrations.AddIndex(
            model_name='worktype',
            index=models.Index(fields=['full_name'], name='directories_full_na_87f9a2_idx'),
        ),
    ]
